### PR TITLE
team1 thumbnails

### PR DESCRIPTION
**Pull request by aalavandhan**
Thumbnails for submitted visualizations. (Team 1)

### CODE REVIEW

**Comment by chrismattmann** [comment]
Thanks @nithinkrishna !

**Comment by chrismattmann** [comment]
@nithinkrishna your site relies on an external site: http://104.236.190.155:9200/polar2/_stats net::ERR_CONNECTION_REFUSED(anonymous function) can you please contribute the JSON and make it all inclusive so it doesn't rely on an external site please? It's not loading now and I want to have control of showing demos and loading it. Thanks!

**Comment by aalavandhan** [comment]
@chrismattmann Yes. They depend on the elastic search running on one of my servers. It's a little patchy, keeps shutting down now and then and needs to be restarted.

Some of the visualizations are dynamic and and are aggregated on the fly by elastic search based on user input and hence there is no way to hardcode the JSON. 

If this is a concern I can remove these specific dynamic visualizations and let the others be.

**Comment by chrismattmann** [comment]
Can you deploy your ES index on my polar.usc.edu Amazon machine? @nithinkrishna

**Comment by aalavandhan** [comment]
@chrismattmann Yes. I can do that. Can you give me access to your AWS machine?

**Comment by chrismattmann** [comment]
yep! @pzimdars can you work with @nithinkrishna over email to get this sorted? Nithin can you email paul.zimdars@jpl.nasa.gov and CC me?

**Comment by chrismattmann** [comment]
@nithinkrishna is this fixed?

**Comment by aalavandhan** [comment]
This is done

Sent from my phone,
Please ignore typos if any.

**Comment by chrismattmann** [comment]
great! thanks for this.

**Pull request merged**
