### PR TITLE
Added viz for hw3 for team 17

### PR DESCRIPTION
**Pull request by mayurimehrotra**
hello Professor @chrismattmann 
Adding d3 visualizations for hw3 for team 17.
Thanks

### CODE REVIEW

**Comment by chrismattmann** [comment]
can you please include a gallery thumbnail for the assgn3 gallery? Thanks @mayurimehrotra

**Comment by mayurimehrotra** [comment]
Hello Professor @chrismattmann
I have updated the images folder to include Team 17 visualization screenshots.
Thanks

**Comment by mayurimehrotra** [comment]
Hi Professor,

I have added the images for assignment 3.

Thanks,
Mayuri Mehrotra
(Team 17)

**Comment by chrismattmann** [comment]
thanks merged! @mayurimehrotra

**Pull request merged**
