### PR TITLE
Team 20 HW3 Evaluation D3 Visualization

### PR DESCRIPTION
**Pull request by adityardesai**
Team 20 HW3 Content Evaluation

### CODE REVIEW

**Comment by chrismattmann** [comment]
hi @adityardesai please include a gallery thumbnail preview and update the assgn3 gallery with a link to this

**Comment by adityardesai** [comment]
@chrismattmann : We are trying to update the page, but not been able to do it. We are facing issues with header part and not getting that displayed even after many tries. We will keep you posted on this. Meanwhile the D3 are available at : http://adityardesai.github.io/Evaluation/index.html

**Comment by chrismattmann** [comment]
thanks for the update @adityardesai please keep working on it.

**Comment by adityardesai** [comment]
@chrismattmann : I took new PR (#161) and made the changes. But not seeing it on our website. I guess you need to merge the changes.

**Comment by aalavandhan** [comment]
Moved https://github.com/USCDataScience/polar.usc.edu/pull/173

**Pull request closed without merging**
