### PR TITLE
CSCI599_HW_ CE_MET_NER TEAM_10 D3 Visualizations - gh-pages

### PR DESCRIPTION
**Pull request by NamithaGS**
D3 Visualizations from Team 10.

### CODE REVIEW

**Comment by lorsposto** [comment]
@NamithaGS Thanks! I'm having some issues. Can you double-check them/confirm or describe how they are supposed to look/work?

screen shot 2016-04-09 at 9 43 29 am

A bit confused by this one, where all the bubbles say "polar.usc.edu/..."
screen shot 2016-04-09 at 9 52 43 am

**Comment by chrismattmann** [comment]
@NamithaGS please reply

**Comment by NamithaGS** [comment]
**Maps_Location_Contribution** : The map shows locations which have contributed to the polar data science. There was a bit problem with the location of the data file. I have updated it and committed.. Could you please check and let me know if it works now?
**Clustering_Sweet_Concepts :** Clustering of documents according to their sweet concepts using circle packing.  The bubbles are supposed to be named with the sweet concept names. I hosted it on a server and checked, I am able to see the correct names ( NER sweet concept names). Can you please recheck this?

capture

**Comment by chrismattmann** [comment]
thanks @NamithaGS I committed this and will test out and get back if there are issues.

**Pull request merged**
