### PR TITLE
Visualization for MIME Diversity Team 24 599 Spring 2016

### PR DESCRIPTION
**Pull request by skashyap7**
Hi,

We have added the htmls,json data and the js scripts as per specification for visualizing the MIME diversity of TREC Polar Data set. It would be great if someone could review and pull our changes.

Thanks,
Tem 24, CSCI 599, Spring 2016

### CODE REVIEW

**Comment by chrismattmann** [comment]
thank you @skashyap7 !

**Comment by chrismattmann** [comment]
@lorsposto FYI

**Comment by lorsposto** [comment]
thanks @skashyap7 !

**Comment by chrismattmann** [comment]
thanks!

**Pull request merged**
