### PR TITLE
Added content enrichment analysis visualizations

### PR DESCRIPTION
**Pull request by balajig17**
@chrismattmann 
Added 6 visualizations for scientific content enrichment. Included as a new tab.

### CODE REVIEW

**Comment by lorsposto** [comment]
@luuj @titusjung @ruthvik947 @janethkim can somebody else take a look at this too? The vizs seem broken to me (I just inserted the iframe at the end of the sce-viz div in the interim). @balajig17 Can you double-check?

From clicking each tab in Firebug:
screen shot 2016-04-05 at 10 26 27 am

**Comment by balajig17** [comment]
@lorsposto fixed the data file reference. Could you check now?

**Comment by lorsposto** [comment]
@balajig17 thanks!

**Comment by lorsposto** [comment]
in process of resolving conflicts

**Pull request merged**
