### PR TITLE
CS-599-Spring-2016-Team-22 MIME ANALYSIS D3 VISUALIZATIONS

### PR DESCRIPTION
**Pull request by harshfatepuria**
I have modified the site to show the D3 visualizations made by our team during the MIME Analysis assignment.

### CODE REVIEW

**Comment by chrismattmann** [comment]
thanks @harshfatepuria. Have a look too at the other submissions which gave a small thumbnail of the visualizations and which add them to the gallery. Great contributions! @lorsposto

**Comment by harshfatepuria** [comment]
Thank you Professor @chrismattmann . I saw the other submissions. All of them look great. I already added a thumbnail entry to the d3-examples.html page

**Comment by chrismattmann** [comment]
thank you @harshfatepuria !

**Comment by lorsposto** [comment]
@harshfatepuria very nice, thanks!

**Pull request merged**
