### PR TITLE
team_11 gh pages

### PR DESCRIPTION
**Pull request by jdramani**

### CODE REVIEW

**Comment by lorsposto** [comment]
@jdramani thank you! The paths for the data used by d3 differ from how they are organize, and for the two circlepacking pages, it is unclear which file to use. Can you update these paths?

**Comment by chrismattmann** [comment]
@jdramani please update the paths

**Comment by jdramani** [comment]
I will do it by the end of the day. I apologize for the delay.

**Comment by lorsposto** [comment]
@jdramani I merged this, but can you check on the two circlepacking pages? Neither work for me.

**Comment by jdramani** [comment]
I will look into it.

**Comment by jdramani** [comment]
@lorsposto The problem is with data file size. It takes too much time to load. If it is not appropriate we can remove those visualizations.

**Pull request merged**
