### PR TITLE
D3 Visualization for Team 7 Assignment 3

### PR DESCRIPTION
**Pull request by anirbanmishra**

### CODE REVIEW

**Comment by lorsposto** [comment]
@anirbanmishra thanks for the PR! Can you quickly resubmit this PR to the gh-pages branch?

**Comment by chrismattmann** [comment]
hi @anirbanmishra please submit this PR from the gh-pages branch, add a thumbnail and please include a gallery thumbnail link to this on the assgn3 page

**Comment by chrismattmann** [comment]
ping @anirbanmishra

**Comment by aalavandhan** [comment]
Moving to https://github.com/USCDataScience/polar.usc.edu/pull/175

**Pull request closed without merging**
