### PR TITLE
Rename barChartData.json to barchartData.json

### PR DESCRIPTION
**Pull request by sandeepkulkarni**
@lorsposto 

Fixing issue of barChart not displaying on Team 16 visualization page on polar.usc.edu.

We think the issue is because the file name is case sensitive on the server. Renaming the file to match the filename in the code.

Regards
Sandeep

### CODE REVIEW

**Comment by chrismattmann** [comment]
thanks @sandeepkulkarni @aravindram!

**Comment by chrismattmann** [comment]
guys this didn't fix it, it's looking for: http://polar.usc.edu/data/team16data/hw2json/barchartData.json

**Comment by chrismattmann** [comment]
can you update? @sandeepkulkarni @aravindram

**Comment by AravindRam** [comment]
Professor @chrismattmann ,

I tried checking the above link and I am able to see the json being fetched. Also, I checked the page now in polar.usc.edu. The bar chart actually gets loaded now. Here is the link to that page 

http://polar.usc.edu/html/team16ev/index.html

So, I guess the issue has been fixed. Please check and let us know if you are still facing some issues.

**Pull request merged**
