### PR TITLE
Team 25 : Evaluating TREC 

### PR DESCRIPTION
**Pull request by manishdwibedy**

### CODE REVIEW

**Comment by chrismattmann** [comment]
can you fix the conflicts @manishdwibedy

**Comment by chrismattmann** [comment]
ping @manishdwibedy

**Comment by manishdwibedy** [comment]
@chrismattmann Hi Professor, I am working on those conflicts. However, I am a tad busy with my last finals on Monday. I would be resolving all the conflicts soon after finishing my finals.

**Comment by chrismattmann** [comment]
thank you @manishdwibedy I appreciate it and that's fine :) 👍 good luck on finals!

**Comment by manishdwibedy** [comment]
Closing this PR. Opened a new PR #165.

**Pull request closed without merging**
