### PR TITLE
Updated visualizations for hw 2 Team 17

### PR DESCRIPTION
**Pull request by swanandj7**
All the d3 visualizations for metadata enrichment hw 2 for team 17

@chrismattmann

### CODE REVIEW

**Comment by lorsposto** [comment]
@swanandj7 thanks for the contribution! Could you place your js, data, css, and html files in the relevant folders, rather than in your top-level Visualizations

**Comment by swanandj7** [comment]
Thank you. I will do that

**Comment by lorsposto** [comment]
@swanandj7 thanks so much!

**Comment by swanandj7** [comment]
@lorsposto  I have done the changes as required. Thanks

**Comment by chrismattmann** [comment]
thanks @swanandj7 and @lorsposto looking good

**Pull request merged**
