### PR TITLE
team 1 visualizations Assignment 1 / Assignment 2 / Assignment 3

### PR DESCRIPTION
**Pull request by aalavandhan**
screen shot 2016-04-05 at 6 31 44 am
screen shot 2016-04-05 at 6 31 59 am
screen shot 2016-04-05 at 6 32 30 am
screen shot 2016-04-05 at 6 32 55 am
screen shot 2016-04-05 at 6 33 18 am
screen shot 2016-04-05 at 6 33 41 am

### CODE REVIEW

**Comment by aalavandhan** [comment]
I just noticed the data for assignment 1 visualizations aren't loading correctly. Don't merge this PR till I fix this. :8ball:

**Comment by aalavandhan** [comment]
screen shot 2016-04-07 at 5 21 24 pm
screen shot 2016-04-07 at 5 21 03 pm
screen shot 2016-04-07 at 5 20 26 pm
screen shot 2016-04-07 at 5 20 02 pm
screen shot 2016-04-07 at 5 19 38 pm

**Comment by aalavandhan** [comment]
Everything Works :+1: 

We can review and merge this. 

http://polar.usc.edu/html/team1/metadata-enrichment/#/
http:/polar.usc.edu/html/team1/mime-diversity-analysis/#/

@chrismattmann

**Comment by lorsposto** [comment]
@nithinkrishna thanks for all these! I'm having trouble with TF-IDF and "Document Count Distribution over Space". Can you double check these?

TF-IDF
screen shot 2016-04-09 at 9 32 15 am

Document Count...
screen shot 2016-04-09 at 9 32 40 am

**Comment by chrismattmann** [comment]
@ruthvik947 @lorsposto any updates?

**Comment by aalavandhan** [comment]
@lorsposto Sorry I've been caught up with some work. I'll update this PR with A3 visualizations aswell today. We can merge them together.

**Comment by aalavandhan** [comment]
Added assignment 3 visualizations. I checked the javascript errors, I don't seem to be getting them. Let me know if you have any issues

@ruthvik947 @lorsposto

**Comment by chrismattmann** [comment]
thanks @nithinkrishna merging!

**Comment by chrismattmann** [comment]
@nithinkrishna can you add some gallery thumbnails for 1, 2 and 3 and send a new PR?

**Comment by aalavandhan** [comment]
@chrismattmann I can do that. Will create a new PR.

**Comment by chrismattmann** [comment]
thanks @nithinkrishna

**Pull request merged**
