### PR TITLE
team26 visualizations for assn3

### PR DESCRIPTION
**Pull request by briancohn**

### CODE REVIEW

**Comment by chrismattmann** [comment]
getting closer @bcohn12 I still get merge conflicts. Can you try and git pull and resolve them locally and then push to usc-bbdl:gh-pages so this PR is updated?

**Comment by briancohn** [comment]
From my forked repo what command can I use to pull in the most updated version of your polar repo?

**Comment by chrismattmann** [comment]
hi @bcohn12 from your forked repo, best bet is to do this:

git pull https://github.com/USCDataScience/polar.usc.edu

That should force a local merge (with conflicts) and tell you which flies conflict. Go into them and look for HEAD messages and messages that show you the conflict inline with the text. Resolve them. Then git add && git commit those files, then git push -u usc-bbdl gh-pages and this PR should be updated.

**Comment by briancohn** [comment]
Instructions worked great! Fixed everything! GitHub says it'll merge cleanly

**Comment by aalavandhan** [comment]
Moving to https://github.com/USCDataScience/polar.usc.edu/pull/171

**Pull request closed without merging**
