### PR TITLE
Added the visualizations for team21. Website can be accessed at http:…

### PR DESCRIPTION
**Pull request by sumedha-12**
Website link for the visualizations: http://cs-server.usc.edu:46737/intro.html
Team-21
Added visualizations in the form of a website.
Will like to thank @chrismattmann for this amazing project experience.
Thank you. 
Snapshots:
cover

### CODE REVIEW

**Comment by chrismattmann** [comment]
please don't link to external websites and please contribute the files directly here @sumedha-12

**Comment by sumedha-12** [comment]
Dear Prof @chrismattmann 
All the files had been contributed under Team21 visualizations.
It was only for your reference.
Thank you for your response.

**Comment by chrismattmann** [comment]
thank you @sumedha-12 got it! Can you please add a thumbnail for the Evaluating Content tab and link to your polar.usc.edu contribution as part of this PR? I will merge as soon as that is done thanks!

**Comment by chrismattmann** [comment]
thank you @sumedha-12 merged!

**Pull request merged**
