### PR TITLE
Added visualisations for Team 26

### PR DESCRIPTION
**Pull request by dhruvbha**
Added visualisations for Team 26 (Pull Request)

### CODE REVIEW

**Comment by chrismattmann** [comment]
@dhruvbha can you please add a gallery preview for the assignment 3 gallery page?

**Comment by chrismattmann** [comment]
@dhruvbha FYI

**Comment by dhruvbha** [comment]
@chrismattmann Professor, This should be done in few hours. I got busy with the preparation for my final exam for the other course. I will update you here as soon as it is done. Is there a particular deadline to do this?

**Comment by chrismattmann** [comment]
thanks @dhruvbha just trying to get it wrapped up before everyone leaves and forgets about it :) a few hours is fine. 👍

**Pull request merged**
