### PR TITLE
D3lookandfeel

### PR DESCRIPTION
**Pull request by titusjung**
d3look feel
d3look feel2
d3look feel3

I put a usc header on each of the d3 examples and fixed the button behaviors so that it is inside the thumbnail not floating on the outside.
Issues remaining:
for team 29b and team29c pages the return link is not working. I suspect that this bug is due to the scrolling nav feature.

### CODE REVIEW

**Comment by lorsposto** [comment]
Thanks for adding the header. What we actually want though is the header to be the same as it is on the splash page. That means we want all of this:

screen shot 2016-03-07 at 10 20 02 am

because we want it to be consistent across all pages

**Comment by luuj** [comment]
Update to above -- Recently changed Nav Bar
screen shot 2016-03-07 at 10 21 48 am

**Comment by titusjung** [comment]
d3look
d3look2

I think this is ready. All teams except team 28 should have the same nav bar as index.hml

**Comment by luuj** [comment]
GJ Titus! A majority of them seem to be working with the exception of Team29b and Team29c. When I view them, the nav-bar links seem to shift up (is this happening to anyone else?).

screen shot 2016-03-09 at 12 12 54 am

I believe this is being caused by the team29-b.css and team29-c.css files (located in the css folder), as they are overwriting bootstrap.min.css's nav-bar settings. If you delete these files (team29-b.css and team29-c.css) and remove their references in both team's HTML files, the issue seems to be fixed. 

However, this changes the look of their pages as the dropdown-menus lose their border and am not sure  how to fix that.

**Comment by titusjung** [comment]
It happens in my end. I'll see what i can do

**Comment by chrismattmann** [comment]
oops did I do that? looks like this is _sorta_ there. Maybe a new PR can be opened to fix the rest. thanks.

**Pull request merged**
