### PR TITLE
feat: adding team 3 assignment 3 files

### PR DESCRIPTION
**Pull request by yashtanna93**

### CODE REVIEW

**Comment by chrismattmann** [comment]
@yashtanna93 this has 3.1k files - does it really need these many files?

**Comment by yashtanna93** [comment]
my bad I'll clean it up today

**Comment by yashtanna93** [comment]
@chrismattmann it's down to half but it's still more because for domain wise analytic, there is a csv file created for each measurement in each domain which goes around 1.4k files for 333 domains

**Comment by chrismattmann** [comment]
Thanks buddy

**Comment by chrismattmann** [comment]
thanks @yashtanna93

**Comment by yashtanna93** [comment]
(Y)

**Pull request merged**
