### PR TITLE
Team 26 Contribution to the Polar.usc.edu dataset

### PR DESCRIPTION
**Pull request by briancohn**
Some beautiful visualizations!

image

image
image

image

image

image

I've literally  never made a pull request with a fork before, so please let me know how I can get better at this (and what I'm missing here).

Cheers!

Brian, Dhruv, and Hang
CS599
brian.cohn@usc.edu

### CODE REVIEW

**Comment by ruthvik947** [comment]
Hey Brian. Those look very cool, but it looks like no files were actually added to the commit. Unless I'm missing something?

**Comment by lorsposto** [comment]
@bcohn12 The submodule doesn't seem to be working. Can you please make a PR with the actual files, instead of a submodule?

**Comment by chrismattmann** [comment]
@bcohn12 please add the files and resubmit to your branch (push to remote branch) which should update this PR.

**Comment by chrismattmann** [comment]
@bcohn12 ping

**Pull request closed without merging**
